project/cms/urls.py
from django.urls import path
from . import views

urlpatterns = [
	path("",views.index),
	path("loggedIn",views.loggedIn),
	path("loggedout",views.loggedout_view),
	path("imagen",views.imagen),
	path("main.css",views.estilo),
    path("<str:llave>",views.get_content)

]

project/project/urls.py
from django.contrib import admin
from django.urls import include, path
from django.contrib.auth.views import LoginView as login

urlpatterns = [
    path("calc/", include("calc.urls")),
    path("cms/", include("cms.urls")),
    path("admin/", admin.site.urls),
    path("login",login.as_view())
]

project/cms/models.py
from django.db import models

class Contenido(models.Model):
   clave = models.CharField(max_length=64)
   valor = models.TextField()
   
   def __str__(self):
   		return str(self.id) + ": " + self.clave + " ---> " + self.valor
   
class Comentario(models.Model):
	contenido = models.ForeignKey(Contenido, on_delete =models.CASCADE)
	titulo = models.CharField(max_length=64)
	cuerpo = models.TextField()
	fecha = models.DateTimeField()
	
	def __str__(self):
		return str(self.id) +": "+ self.titulo
		

project/cms/views.py
from django.shortcuts import render
from django.http import HttpResponse, Http404
from .models import Contenido, Comentario
from django.views.decorators.csrf import csrf_exempt
from django.template import loader
from django.contrib.auth import logout
from django.shortcuts import redirect
from django.utils import timezone

@csrf_exempt
def get_content(request,llave):
	if request.method == "PUT":
		valor = request.body.decode("utf-8")

	if request.method == "POST":
		action = request.POST["action"]
		if action == "Enviar Contenido":
			valor = request.POST['valor']
			try:
				content = Contenido.objects.get(clave=llave)
				content.valor = valor
				content.save()
			except Contenido.DoesNotExist:
				content = Contenido(clave=llave, valor=valor)
				content.save()

		elif action == "Enviar Comentario":
			contenido = Contenido.objects.get(clave=llave)
			titulo = request.POST["titulo"]
			cuerpo = request.POST["cuerpo"]
			fecha = timezone.now()

			q = Comentario(contenido= contenido, titulo = titulo, cuerpo = cuerpo, fecha = fecha)
			q.save()

		
	try:
		content = Contenido.objects.get(clave=llave)
		context = {"content": content}
	except Contenido.DoesNotExist:
		return render(request,"cms/new.html",{})

	return render(request,"cms/content.html",context)
	
def index(request):
	
	content_list = Contenido.objects.all()
	template = loader.get_template("cms/index.html")
	context = {
		"content_list" : content_list
	}

	return HttpResponse(template.render(context,request))
	
def loggedIn(request):
	if request.user.is_authenticated:
		respuesta = "Logged in as " + request.user.username
	else:
		respuesta = "No estás autenticado. <a href =/login>Autentícate</a>"
	return HttpResponse(respuesta)
	
def loggedout_view(request):
	logout(request)
	return redirect("/cms/")

def imagen(request):
	template = loader.get_template("cms/plantilla.html")
	context = {}

	return HttpResponse(template.render(context,request))

def estilo(request):
    return render(request, "cms/main.css" , content_type="text/css")

project/cms/templates/cms/base.html
{% load static %}
<head>
    <meta charset="UTF-8">
    <title>Mi Django CMS</title>
</head>
<body>

<h1>DJANGO CMS</h1>
<img src="{% static "cms/URJC_logo.png" alt="Logo de la URJC" width="200" height="100" %}">
<hr>

{% block cuerpo %}
{%endblock}

</body>
</html>

project/cms/templates/cms/content.html
<head>
	<link rel="stylesheet" type="text/css" href="main.css"/>
</head>

<body>
El valor de la llave es: {{ content.valor }}

{% for comentario in content.comentario_set.all %}

	<p><b>Titulo:</b> {{comentario.titulo}}
		<br><b>Cuerpo:</b>  {{comentario.cuerpo}}
		<br><b>Fecha:</b>  {{comentario.fecha}}

{% endfor %}

<p>Introducela
<p>
<form action = "" method = "POST">
	valor :<input type = "text" name = "valor">
	<br/> <input type = "submit" name = "action" value = "Enviar Contenido">

</form>

<p><form action = "" method = "POST">
	<br>Titulo :<input type = "text" name = "titulo">
	<br>Cuerpo :<input type = "text" name = "cuerpo">
	</br> <input type = "submit" name = "action" value = "Enviar Comentario">

</form>
</body>

</html>

project/cms/templates/cms/new.html
<head>
	<link rel="stylesheet" type="text/css" href="main.css"/>
</head>

{%if request.user.is_authenticated %}
<p>Eres {{request.user.username}}. Bienvenido!!</p>
<p>Plantilla para introducir un nuevo usuario</p>

<p>
<form action = "" method = "POST">
	valor :<input type = "text" name = "valor">
	<br/> <input type = "submit" name = "action" value = "Enviar Contenido">

</form>

{% else %}
	No estás autenticado. <a href =/login>Autentícate</a>

{% endif %}

project/cms/templates/cms/plantilla.html
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <title>Una imagen</title>
</head>
<body>

{% load static %}
<img src="{% static "cms/URJC_logo.png" %}" alt="Logo de la URJC" width="200" height="100">

</body>
</html>

project/templates/cms/index.html
<html>

<head>
	<title> ESTE SERÁ EL TÍTULO</title>
</head>

<body>

{% if content_list %}
<ul>
	{% for content in content_list %}
	
		<li><a href ="/cms/{{ content.clave }}">{{ content.clave }}</a> -- {{ content.id }} -- {{content.valor}} </li>
		
	{% endfor %}
</ul>

{% else %}

	<p> No hay contenido </p>
	
{% endif %}

</body>

</html>